-- Security master, daily prices, and the substitute graph used by tax-loss harvesting.
--
-- Owned by market-data-service. The schema itself is created by infra/init-db.sql when the
-- Postgres container first initialises; everything inside it comes from these migrations.

CREATE TABLE security (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(10)  NOT NULL,
    name   VARCHAR(128) NOT NULL,
    sector VARCHAR(64)  NOT NULL,

    CONSTRAINT uq_security_ticker UNIQUE (ticker)
);

COMMENT ON TABLE security IS 'The investable universe. Tickers are labels only — prices are simulated.';

-- One row per security per trading day. The composite primary key is the natural key here:
-- a security cannot have two closing prices on the same date, and making that a constraint
-- rather than a convention means a double-run of the simulator fails loudly instead of
-- silently doubling a day's price history.
CREATE TABLE price (
    security_id BIGINT        NOT NULL,
    price_date  DATE          NOT NULL,
    close       NUMERIC(18,4) NOT NULL,

    CONSTRAINT pk_price PRIMARY KEY (security_id, price_date),
    CONSTRAINT fk_price_security FOREIGN KEY (security_id) REFERENCES security (id) ON DELETE CASCADE,
    -- A zero or negative price is never a legitimate value and would silently corrupt every
    -- downstream weight and market-value calculation.
    CONSTRAINT ck_price_positive CHECK (close > 0)
);

-- "If we have to sell X for tax reasons, what do we buy instead?" Ranked, because the first
-- choice may itself be excluded or wash-sale blocked for a given account, and the engine then
-- needs a second and third option.
CREATE TABLE substitute (
    security_id    BIGINT   NOT NULL,
    substitute_id  BIGINT   NOT NULL,
    rank           SMALLINT NOT NULL,

    CONSTRAINT pk_substitute PRIMARY KEY (security_id, substitute_id),
    CONSTRAINT fk_substitute_security FOREIGN KEY (security_id) REFERENCES security (id) ON DELETE CASCADE,
    CONSTRAINT fk_substitute_target FOREIGN KEY (substitute_id) REFERENCES security (id) ON DELETE CASCADE,
    -- Buying back the security you just sold at a loss is the exact thing the wash-sale rule
    -- forbids. Making it impossible at the schema level means no code path can produce it.
    CONSTRAINT ck_substitute_not_self CHECK (security_id <> substitute_id),
    -- Ranks must be unambiguous: two rank-1 substitutes would make "the best substitute" a
    -- non-deterministic choice, and a rebalance that is not reproducible cannot be audited.
    CONSTRAINT uq_substitute_rank UNIQUE (security_id, rank)
);

-- Latest-price lookups scan by security and sort by date descending. The primary key already
-- covers (security_id, price_date); this index serves the "all securities on the latest date"
-- query that the price cache warms from.
CREATE INDEX idx_price_date ON price (price_date DESC);
