package com.taxlot.marketdata;

import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * Real Postgres and real Redis for integration tests.
 *
 * <p>Uses the <b>singleton container</b> pattern — containers are started once in a static
 * initialiser and shared by every test class that extends this. The alternative, JUnit's
 * {@code @Testcontainers} lifecycle with {@code @Container} fields, starts and stops a fresh
 * pair per test class, which costs several seconds each time and adds up fast as the suite
 * grows. The JVM tears these down on exit, and Testcontainers' Ryuk sidecar cleans up anything
 * left behind if the JVM is killed.
 *
 * <p>These are real containers, not H2 or an embedded Redis. The migrations use Postgres-specific
 * syntax ({@code GENERATED BY DEFAULT AS IDENTITY}, window functions in the seed), and a test
 * against a different database would prove the code works somewhere it will never run.
 */
public abstract class AbstractIntegrationTest {

    protected static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>(DockerImageName.parse("postgres:16-alpine"))
                    .withDatabaseName("taxlot")
                    .withUsername("taxlot")
                    .withPassword("taxlot");

    protected static final GenericContainer<?> REDIS =
            new GenericContainer<>(DockerImageName.parse("redis:7-alpine")).withExposedPorts(6379);

    static {
        POSTGRES.start();
        REDIS.start();
    }

    @DynamicPropertySource
    static void registerContainerProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        registry.add("spring.data.redis.host", REDIS::getHost);
        registry.add("spring.data.redis.port", () -> REDIS.getMappedPort(6379));
    }
}
